[package]
name = "scatac-barcode-splitter"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow          = "1"
clap            = { version = "4.5", features = ["derive"] }
crossbeam-channel = "0.5"
flate2          = "1"          # 仍需 gzip 解压
fastq           = "0.6"        # ← 新增：fastq‑rs 主角