[package]
name = "scatac-barcode-splitter"
version = "0.1.0"
edition = "2021"

[dependencies]
flate2 = "1.0"
rayon = "1.7"
clap = { version = "4.0", features = ["derive"] }
crossbeam-channel = "0.5"
anyhow = "1.0"